
# Типа настойки.
# Юникод в ключах использовать нельзя. Точки в ключах использовать нельзя:
# A key may be either bare, quoted or dotted.
# Bare keys may only contain ASCII letters, ASCII digits, underscores, and dashes (A-Za-z0-9_-). 
# Note that bare keys are allowed to be composed of only ASCII digits, e.g. 1234, but are always interpreted as strings.
#
[MyGbSettings]
dbserver = "127.0.0.1"
dbuser = "root"
dbpassword = "qwerty"
dbdb = "julia_test"

